#!/usr/bin/env python
import subprocess as sp
from pymongo import MongoClient
client = MongoClient()
db = client['mydb']

output = sp.check_output(['git log -1 --format="%H,%s"'],shell=True).decode(encoding='ascii')
sha,msg = output.split(',')
post = {"sha1":sha, "commit_msg":msg}
db.mydb.insert_one(post)
